In [6]:
import numpy as np

In [20]:
arr=np.zeros((5,5))

In [21]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [25]:
x=np.array([10,20,30,40,50,60]).reshape((2,3))

x


array([[10, 20, 30],
       [40, 50, 60]])

In [28]:
x.size

6

In [29]:
x.dtype

dtype('int32')

In [33]:
a=np.array([1,2,3])
b=np.array([4,5,6])


In [34]:
add=a+b
add

array([5, 7, 9])

In [35]:
sub=a-b
sub

array([-3, -3, -3])

In [36]:
multiply=a*b
multiply

array([ 4, 10, 18])

In [39]:
div=a//b
div

array([0, 0, 0], dtype=int32)

In [70]:
z=np.arange(10,90).reshape(10,8)

z

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73],
       [74, 75, 76, 77, 78, 79, 80, 81],
       [82, 83, 84, 85, 86, 87, 88, 89]])

In [77]:
z[:,3]

array([13, 21, 29, 37, 45, 53, 61, 69, 77, 85])

In [78]:
z[2,:]

array([26, 27, 28, 29, 30, 31, 32, 33])

TypeError: 'builtin_function_or_method' object is not subscriptable